name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # You can specify a different version if needed

    - name: Install dependencies
      run: |
        # If you have dependencies, you can install them here
        # pip install -r requirements.txt
        echo "No dependencies to install."
        git add hello.py .github/workflows/python-app.yml
git commit -m "Add hello.py and GitHub Actions workflow"
git push origin main

    - name: Run script
      run: python hello.py
